# Generated by Django 5.1.2 on 2024-12-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbus', '0006_alter_bus_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='cant_pasajeros_max',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='bus',
            name='cant_pasajeros_min',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='atractivoxparada',
            name='atractivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atractivoxparada_Atractivo', to='appbus.atractivo'),
        ),
        migrations.AlterField(
            model_name='atractivoxparada',
            name='parada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atractivoxparada_Parada', to='appbus.parada'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='estado_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_estadobus', to='appbus.estadobus'),
        ),
        migrations.AlterField(
            model_name='ordenparada',
            name='parada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_parada', to='appbus.parada'),
        ),
        migrations.AlterField(
            model_name='ordenparada',
            name='recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_recorrido', to='appbus.recorrido'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='tipo_parada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parada_tipoparada', to='appbus.tipoparada'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_bus', to='appbus.bus'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_chofer', to='appbus.chofer'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado_viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_estadoviaje', to='appbus.estadoviaje'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_recorrido', to='appbus.recorrido'),
        ),
    ]
