# Generated by Django 4.2.13 on 2024-12-04 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbus', '0007_bus_cant_pasajeros_max_bus_cant_pasajeros_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='usuarios_anotados',
            field=models.ManyToManyField(blank=True, related_name='viajes_anotados', to=settings.AUTH_USER_MODEL),
        ),
    ]
