# Generated by Django 4.2.13 on 2024-12-07 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbus', '0008_viaje_usuarios_anotados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='cant_pasajeros_max',
            new_name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='cant_pasajeros_min',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='usuarios_anotados',
            field=models.ManyToManyField(related_name='viajes_anotados', to=settings.AUTH_USER_MODEL),
        ),
    ]
