# Generated by Django 4.2.13 on 2024-12-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbus', '0009_rename_cant_pasajeros_max_bus_capacidad_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
